kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: che-admin-binding
  namespace: che
subjects:
- kind: ServiceAccount
  name: che
  namespace: che
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
