---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-claim-example
  annotations:
    volume.beta.kubernetes.io/storage-class: disk-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: disk-storage

